FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY DataDep.csproj .
RUN dotnet restore

COPY . .
RUN dotnet build -c Release --no-restore

RUN dotnet publish -c Release --no-restore -o /app/publish

CMD ["sleep", "1000"]