"""New image model

Revision ID: b0495f711a17
Revises: ef581bdccccc
Create Date: 2024-02-04 17:51:21.859580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0495f711a17'
down_revision = 'ef581bdccccc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###