FROM php:8.0-fpm

WORKDIR /opt/app
COPY . /var/www/html/

RUN apt update
RUN apt install python3 python3-pip -y
WORKDIR /var/www/html/generator
RUN pip3 install -r requirements.txt
WORKDIR /var/www/html

EXPOSE 9000