FROM ubuntu as cuberite

RUN apt update && apt -y install curl openssl build-essential cmake python3 && \
    rm -rf /var/lib/apt/lists/*
        
ENV CUBERITE_USERNAME="admin" \
    CUBERITE_PASSWORD="cuberite" \
    PGID="46372" \
    PUID="46372" \
    HTTPS=0 \
    CREATE_SETTINGS_INI=1 \
    DEFAULT_LOGIN_PERMISSIONS=1 \
    AUTHENTICATION_AUTHENTICATE=0 \
    AUTHENTICATION_ALLOWBUNGEECORD=0 \
    AUTHENTICATION_SERVER='sessionserver.mojang.com' \
    AUTHENTICATION_ADDRESS='/session/minecraft/hasJoined?username=%USERNAME%&serverId=%SERVERID%' \
    MOJANGAPI_NAMETOUUIDSERVER='api.mojang.com' \
    MOJANGAPI_NAMETOUUIDADDRESS='/profiles/minecraft' \
    MOJANGAPI_UUIDTOPROFILESERVER='sessionserver.mojang.com' \
    MOJANGAPI_UUIDTOPROFILEADDRESS='/session/minecraft/profile/%UUID%?unsigned=false' \
    SERVER_DESCRIPTION='Cuberite - in C++!' \
    SERVER_SHUTDOWNMESSAGE='Server shutdown' \
    SERVER_MAXPLAYERS=100 \
    SERVER_HARDCOREENABLED=0 \
    SERVER_ALLOWMULTILOGIN=0 \
    SERVER_RESOURCEPACKURL='' \
    SERVER_PORTS=25565 \
    SERVER_ALLOWMULTIWORLDTABCOMPLETION=1 \
    SERVER_DEFAULTVIEWDISTANCE=10 \
    RCON_ENABLED=0 \
    ANTICHEAT_LIMITPLAYERBLOCKCHANGES=1 \
    PLAYERDATA_LOADOFFLINEPLAYERDATA=0 \
    PLAYERDATA_LOADNAMEDPLAYERDATA=1 \
    WORLDS_DEFAULTWORLD='world' \
    WORLDPATHS_WORLD='world' \
    PLUGINS_CORE=1 \
    PLUGINS_CHATLOG=1 \
    PLUGINS_PROTECTIONAREAS=0 \
    PLUGINS_LOGIN=0 \
    DEADLOCKDETECT_ENABLED=1 \
    DEADLOCKDETECT_INTERVALSEC=20

COPY cuberite/ /opt/cuberite

# VOLUME /cuberite 

WORKDIR /cuberite
RUN cmake -DCMAKE_BUILD_TYPE=RELEASE /opt/cuberite
RUN make -j`nproc`

COPY nwatch/ /cuberite/Server/Plugins/nwatch
COPY auth/ /cuberite/Server/Plugins/auth
# COPY world/ /cuberite/Server/world
COPY files/entrypoint.sh    /entrypoint.sh

# RUN rm -rf /opt/cuberite

EXPOSE 8080 25565
################# VSFTPD

RUN set -x \ 
    && apt-get update \
    &&  apt-get install -y --no-install-recommends apache2-utils build-essential db5.3-util whois libpam0g-dev libpam-pwdfile

COPY vsftpd-2.3.4/ /vsftpd_raw/
WORKDIR /vsftpd_raw/
RUN make

RUN mkdir /var/www
RUN chmod -R 755 /var/www
RUN chown -R www-data /var/www

RUN echo "www-data" >> /etc/vsftpd.chroot_list
RUN chown -R www-data /etc/vsftpd.chroot_list
RUN chmod 755 /etc/vsftpd.chroot_list
RUN echo 'www-data:alpine' | chpasswd

COPY vsftpd/vsftpd*.conf /etc/
COPY vsftpd/vsftpd_virtual /etc/pam.d/
COPY vsftpd/*.sh /

RUN echo "ftp             21/tcp" >> "/etc/services"
RUN mkdir -p /usr/share/empty

# VOLUME ["/etc/vsftpd", "/srv"]

EXPOSE 21 4559 4560 4561 4562 4563 4564

# WORKDIR /cuberite/Server

ENTRYPOINT [ "/entry.sh", "/entrypoint.sh", "/cuberite/Cuberite"]

# docker run --publish 25565:25565 --publish 21:21 -p 60000-60100:60000-60100/tcp -p 6200:6200 --name cuberite --tty nimda_cuberite
