version: "3.7"

services:
    nginx:
        build:
            context: .
            dockerfile: ./nginx/dockerfile
        depends_on:
            - ssb_backend
        container_name: nimda_ssb_nginx
        ports:
            - 8500:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/logs:/var/log/nginx
            - ./tmp/:/etc/tmp:ro

    ssb_backend:
        build:
            context: ./backend/
            dockerfile: dockerfile
        container_name: nimda_ssb_b
        command: bash -c "cd generator && python3 generateRandomDB.py && cd .. && php -S 0.0.0.0:9000"
        volumes:
            - ./backend/px.db:/var/www/html/px.db
            - ./tmp/:/var/www/html/tmp



volumes:
    nimda_db_data:
        driver: local
