FROM php:latest

COPY *.php /var/www/html/

# RUN apt-get update && apt-get install -y \
#     nano \
#  && rm -rf /var/lib/apt/lists/*

RUN echo "error_reporting = E_ALL & ~E_WARNING  & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED" >> /usr/local/etc/php/php.ini
WORKDIR /var/www/html/
RUN chown -R www-data:www-data /var/www/html/
EXPOSE 8000

CMD ["php", "-S", "0.0.0.0:8000"]