FROM alpine:latest

RUN apk --no-cache add python3 py3-pip

WORKDIR /app

COPY requirements.txt .

RUN python3 -m venv venv
ENV PATH="/app/venv/bin:$PATH"

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mv XFold /opt
RUN ln -s /opt/XFold/XFold /usr/bin/xfold

RUN adduser -D limiteduser
USER limiteduser

ENV FLASK_APP=main.py

EXPOSE 8000

CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]
